# app netlify.toml
[build]
  command = "npm run build"
  functions = "functions"
  publish = "public"

[build.environment]
  APP_SPECIFIC_FLAG = "true"

[[redirects]]
  from = "/client/*"
  to = "/index.html"
  status = 200